import "tailwindcss/tailwind.css";


export const metadata = {
  title: "Age Calculator App",
  description: "Generated by Next.js and Talwind and tsx",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
      <body >{children}</body>
      </body>
    </html>
  );
}
